services:
  - type: web
    name: drug-management-system
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/spring-web-app-1.0-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17.0.0
      - key: SPRING_PROFILES_ACTIVE
        value: prod 